## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [13]:
wine = datasets.load_wine()
boston = datasets.load_boston()
breast_cancer = datasets.load_breast_cancer()
print(wine.data)
print(wine.target)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [17]:
# 切分訓練集/測試集
x_train1, x_test1, y_train1, y_test1 = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train1, y_train1)

# 將測試資料丟進模型得到預測結果
y_pred1 = regr.predict(x_test1)
print(y_pred1)

[ 1.58769368  1.64856583 -0.47991062  0.25773674  0.54105137  2.03303343
 -0.0836996   0.87892808 -0.13017211  1.04989241  1.09805584 -0.41946662
  1.85033782  2.08422586  0.07114954  0.99184361  0.34809227  0.93578595]


In [18]:
# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test1, y_pred1))

Coefficients:  [-1.05070118e-01  2.91905944e-02 -1.77867960e-01  4.31547165e-02
  1.01210209e-04  1.49892356e-01 -3.70827482e-01 -2.59847929e-01
  4.22928548e-02  7.46189422e-02 -1.58479025e-01 -2.64616732e-01
 -7.43793043e-04]
Mean squared error: 0.07


In [19]:
# 切分訓練集/測試集
x_train2, x_test2, y_train2, y_test2 = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train2, y_train2)

# 將測試資料丟進模型得到預測結果
y_pred2 = regr.predict(x_test2)
print(y_pred2)

[11.46030778 26.80269335 17.43478925 17.5563101  37.39156424 25.07675556
 31.05825852 20.30845531 19.66757374 22.82655375 28.47083056 28.53331605
 18.72883256 33.11375161 21.34282974 15.20554693 21.57309275 10.92841589
 11.69603405 13.54311508  5.07126801 17.40464043 20.69379268 22.72981238
 16.4634139  20.42666271 17.53377349 14.22644356 21.56292745 17.33136115
 14.28888479 23.92829804 34.31523522 22.03799035 17.47895779 20.20386005
 30.70896335 35.21599528 24.07063567 24.51445184 36.77425366 33.15265201
 19.67545976 31.93505104 33.55222906 25.59147737 40.59239607 17.99555017
 19.92780188 23.65319423 33.48950986]


In [20]:
# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test2, y_pred2))

Coefficients:  [-1.25856659e-01  4.84257396e-02  1.84085281e-02  3.08509569e+00
 -1.73277018e+01  3.61674713e+00  2.19181853e-03 -1.49361132e+00
  3.19979200e-01 -1.27294649e-02 -9.27469086e-01  9.50912468e-03
 -5.33592471e-01]
Mean squared error: 17.04


In [21]:
# 切分訓練集/測試集
x_train3, x_test3, y_train3, y_test3 = train_test_split(breast_cancer.data, breast_cancer.target, test_size=0.1, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train3, y_train3)

# 將測試資料丟進模型得到預測結果
y_pred3 = regr.predict(x_test3)
print(y_pred3)

[ 0.63796023  1.00975225 -0.24154207  0.31882183  0.62338577  0.7172752
  0.96667529  1.08194491  0.50007807  0.74341563  0.11200564  0.75857091
  0.77203365  0.76613004  0.82173711  1.13253367  0.89628541  0.74372738
  1.08459726  0.83979931  1.05494655  0.71308278  0.15299854  0.95272799
  0.77155526  0.29092207  0.96485271  1.17780511  0.77171142  0.99260931
  1.12371459  1.08185097  0.77298434  0.6915128   0.96600069 -0.03501439
  1.52095785  0.32721916  0.16148717  0.36454545  0.46306336  0.97688699
  0.44979616  0.69914648  0.85040068  0.83323006  0.70974232 -0.21368642
  1.04358993 -0.22131824 -0.07846172  0.56201526  1.10934441  0.6104222
  0.80289195  1.01049821  0.15559779]


In [22]:
# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test3, y_pred3))

Coefficients:  [ 1.68835597e-01 -2.47104416e-04 -1.40455380e-02 -5.28945672e-04
 -8.75672914e-01  3.69533926e+00 -1.50766134e+00 -1.00150567e+00
  2.06985795e-01 -2.21306041e+00 -5.52724261e-01  3.21126180e-02
  3.22937249e-02  1.13272268e-03 -1.82622595e+01 -9.76169145e-01
  3.63416824e+00 -1.31316890e+01 -9.83129744e-01  1.52838890e+01
 -2.02142885e-01 -1.14860447e-02  9.09100946e-04  1.12968308e-03
  1.10041018e-01  1.55490914e-01 -4.55942288e-01 -1.22118889e-01
 -7.62376123e-01 -4.88123450e+00]
Mean squared error: 0.06
